

# [theme]

# # Primary accent for interactive elements
# primaryColor = '#7792E3'

# # Background color for the main content area
# backgroundColor = '#273346'

# # Background color for sidebar and most interactive widgets
# secondaryBackgroundColor = '#B9F1C0'

# # Color used for almost all text
# textColor = '#FFFFFF'

# # Font family for all text in the app, except code blocks
# # Accepted values (serif | sans serif | monospace) 
# # Default: "sans serif"
# font = "sans serif"

[theme]
base = "dark"                       # Use the built-in dark base theme
primaryColor = "#0E639C"            # Accent color (buttons, active sidebar items)
backgroundColor = "#1E1E1E"         # App background
secondaryBackgroundColor = "#2E2E2E" # Sidebar background or secondary elements
textColor = "#FFFFFF"                # Text color
font = "sans serif"                  # Font style

